# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123  
    ports:
      - 3366:3306

#docker exec -it sql-db-1 mysql -u root -p
#mysql -u root

#docker cp /home/newton/Downloads/curso_sql-main/1_intro/empresa.sql sql-db-1:/tmp/empresa.sql

#docker exec -it sql-db-1 /bin/bash

#mysql -u root -p

#source /tmp/empresa.sql;
